{% set name = "click-rich-help" %}
{% set version = "0.3.0" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-rich-help-{{ version }}.tar.gz
  sha256: cb49da548265905f9888a47c55224878cd643bad0451b3a3b1758664f03f61c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - click >=8.0,<9.0
    - python >=3.6,<4.0
    - rich >=10.0

test:
  imports:
    - click_rich_help
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/daylinmorgan/click-rich-help
  summary: make a beautiful click app with rich
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - daylinmorgan
